name: Build Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install meson ninja-build libsdl2-dev

    - name: Build
      run: |
        meson setup build -Dthorvg_subproject=thorvg-main -Dthreads=true
        ninja -C build

    - name: Run LottieExpressions 5000 Ticks
      run: |
        ./build/src/LottieExpressions sw 0

  